version: "3.7"
services:
  parachain-2000-0:
    ports:
      - 9946:9944
      - 9935:9933
      - 30335:30333
    volumes:
      - parachain-2000-0:/acala/data
    build:
      context: .
      dockerfile: parachain-2000.Dockerfile
    command:
      - --dev
      - --base-path=/acala/data
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2000-0
      - --collator
      - --rpc-methods=unsafe
      - --force-authoring
      - --wasm-execution=compiled
      - --execution=wasm
      - --alice
      - --node-key=b7a9ab817a91b2d70f3aef9865c34aa28052e81bbfdc3bb25c9b8ad09fc9d56c
      - --listen-addr=/ip4/0.0.0.0/tcp/30333
    environment:
      RUST_LOG: sc_basic_authorship=trace,cumulus-consensus=trace,cumulus-collator=trace,collator_protocol=trace,collation_generation=trace,aura=debug

volumes:
  ? parachain-2000-0